#ifndef TASK_22C_H__
#define TASK_22C_H__

enum {
	BLUETOOTH_CMD_START_QUESTION1 = 0x01,
	BLUETOOTH_CMD_START_QUESTION2,
	BLUETOOTH_CMD_START_QUESTION3,  
	BLUETOOTH_CMD_START_QUESTION4, 
	BLUETOOTH_CMD_RECONNECT_QUESTION4, 
	BLUETOOTH_CMD_TEST_CONNECT,
	BLUETOOTH_CMD_STOP,    
	BLUETOOTH_CMD_COUNT,
};

#define C22_BASE_SPEED 40
#define STOP_MARK_CLEARANCE_CM 40

void init_task_table(void);
void menu_init_and_create(void);


#endif 
